<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TendrilIconKind>named</TendrilIconKind>
    <TendrilIconValue>Bell</TendrilIconValue>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../Ivy.Tendril.Plugin.Extended.Abstractions/Ivy.Tendril.Plugin.Extended.Abstractions.csproj" />
  </ItemGroup>

</Project>
